 
export * from "./OperationActions"
export * from "./ActionsCountDown"
export * from "./cardsActionCountDown"
export * from './refreshActionCountDown'
export * from "./FieldStatusActions"
export * from "./ServerAction"


export const CONSTANTS = {
    ADD_LIST_OPERATION: "ADD_LIST_OPERATION",
    ADD_CARD_OPERATION: "ADD_CARD_OPERATION",
    ADD_CARD_COUNTDOWN: "ADD_CARD_COUNTDOWN",
    ADD_EVENT_COUNTDOWN: "ADD_EVENT_COUNTDOWN",
    DRAG_HAPPENED_COUNTDOWN: "DRAG_HAPPENED_COUNTDOWN",
    REFRESH_COUNTDOWN: "REFRESH_COUNTDOWN",
    DELETE_EVENT_COUNTDOWN: "DELETE_EVENT_COUNTDOWN",
    DELETE_ENTITY_COUNTDOWN: "DELETE_ENTITY_COUNTDOWN",
    ADD_ENTITY_COUNTDOWN: "ADD_ENTITY_COUNTDOWN",
    DELETE_BUTTON_FIELDSTATUS: "DELETE_BUTTON_FIELDSTATUS",
    ADD_BUTTON_FIELDSTATUS :"ADD_BUTTON_FIELDSTATUS",
    ADD_CARD_FIELDSTATUS: "ADD_CARD_FIELDSTATUS",
    DELETE_CARD_FIELDSTATUS: "DELETE_CARD_FIELDSTATUS",
    DELETE_LIST_FIELDSTATUS: "DELETE_LIST_FIELDSTATUS",
    ADD_LIST_FIELDSTATUS: "ADD_LIST_FIELDSTATUS",
    CHANGE_STATE : "CHANGE_STATE",
    SAVE_STATE : "SAVE_STATE",
    SET_NEW_TABLE:"SET_NEW_TABLE",

};

